name: build container image
on:
  push:
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: build image
        run: docker build . --file dockerfile --tag webapp

      - name: log in to registry
        run: echo "${{ secrets.github_token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: push image
        run: |
          image_id=ghcr.io/kacaii/senac-brigade-server
          tag="$image_id":$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          docker tag webapp "$tag"
          docker push "$tag"
